MODS    += ${BUILD_OBJS}/log.o
#MODS    += ${BUILD_OBJS}/dcell.o

MAIN_OUT = main

# TEST_OUT = test_dlink

include mk.tpl

CXXFLAGS += -Wno-unused-label

# Main is tested
# $(eval $(call TEST_template,${MAIN_OUT}))

# TEST is tested
# $(eval $(call CMD_template,${TEST_OUT}))
# $(eval $(call TEST_template,${TEST_OUT}))

